name: prod-deploy
on:
#Commented out on schedule for the time being till we have the production environment ready.
  schedule:
    - cron: '*/20 * * * *' # every 20th min
  workflow_dispatch:
    inputs:
      source:
        description: "Artifact Source"
        required: true
        type: choice
        options:
          - releases
      artifact-identifier:
        description: release tag
        type: string
        required: true
permissions:
  id-token: write
  contents: read
  actions: write
jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: inchworksinc/releases-demo/.github/workflows/deploy.yml@main
    with:
      template_file_path: infrastructure/app-service.bicep
      package: app
      slot_name: staging
      source: ${{ inputs.source }}
      artifact-identifier: ${{ inputs.artifact-identifier }}
    secrets: inherit
  scheduledDeploy:
    if: ${{ github.event_name == 'schedule' }}
    uses: inchworksinc/releases-demo/.github/workflows/build-and-deploy.yml@main
    with:
      template_file_path: infrastructure/app-service.bicep
      slot_name: staging
    secrets: inherit

    


